BUILD: rename distgit to 'make dist' and support EXTRA_DIST
Signed-off-by: Tim Janik <timj@gnu.org>

diff --git a/Makefile.decl b/Makefile.decl
--- a/Makefile.decl
+++ b/Makefile.decl
@@ -47,6 +47,22 @@ local-ETAGS:
 XVFB_MISSING = $(shell test `echo $${DISPLAY:-:0} | sed 's/^[^:]*:\([0-9]\+\).*/\1/'` -ge 99 || echo missingxvfb)
 X11_ENV = $(if $(XVFB_MISSING), xvfb-run -a -s "-screen 0 800x600x24") /usr/bin/env
 
+# == extra-gitdist ==
+extra-gitdist:
+	@test -z "$(EXTRA_DIST)" || echo "  TAR      $(patsubst %, $(subdir)/%, $(EXTRA_DIST))"
+	$(Q) test -w "$(EXTRA_GITDIST_DIR)" || { echo '$@: missing EXTRA_GITDIST_DIR' >&2; false; }
+	@for subdir in $(SUBDIRS) ; do						\
+	  test "$$subdir" = '.' ||						\
+	    $(MAKE) $(AM_MAKEFLAGS) -C "$$subdir"				\
+		$(if $(findstring 1, $(V)),, --no-print-directory) $@ ||	\
+	    exit 1 ;								\
+	done
+	$(Q) for file in $(EXTRA_DIST) ; do					\
+	  cp -a --parent "$$file" "$(EXTRA_GITDIST_DIR)/$(subdir)/" ||		\
+	  exit 1;								\
+	done
+.PHONY: extra-gitdist
+
 # === distfile-list ===
 # recursive rule supported by all Makefiles to generate a list of all files
 # listed as DISTFILES. this asserts a writable file named $DISTFILE_LIST.
