plic/: install plic, moved tests to plic/tests/.
* plic/Makefile.am: reworked all rules, build and install plic-VERSION.
create plic -> plic-VERSION link in bindir upon installation.

* plic/.gitignore: shut up about build files.

* plic/tests/Makefile.am: moved all plic test rules here.

* plic/tests/testfail.idl: moved here from ../testfail.idl.

* plic/tests/testpass.idl: moved here from ../testpass.idl.

diff --git a/plic/tests/Makefile.am b/plic/tests/Makefile.am
--- a/plic/tests/Makefile.am
+++ b/plic/tests/Makefile.am
@@ -1,35 +1,26 @@
-# plic - Pluggable IDL Compiler
+# plic tests
+# Copyright (C) 2007 Tim Janik
 #
 ## GNU Lesser General Public License version 2 or any later version.
+include $(top_srcdir)/Makefile.decl
 
-srcdir=.
-
-all:	plic.py
-	$(MAKE) $(AM_MAKEFLAGS) check
-
-plic.py: plic.g
-	yapps plic.g xgen-$(@F) 2>&1 | tee xgen-$(@F).errors
-	@! grep -q '.' xgen-$(@F).errors	# catch all yapps errors & warnings
-	sed 's/^from yapps import runtime$$//' -i xgen-$(@F)	# plic.g has all imports
-	chmod +x xgen-$(@F)
-	cp xgen-$(@F) $@
-	rm -f xgen-$(@F) xgen-$(@F).errors
+PLIC = $(top_builddir)/plic/plic-@LT_RELEASE@
 
 check:	check-pass check-fail
 
-check-pass:	plic.py testpass.idl
-	./plic.py $(srcdir)/testpass.idl
+check-pass:	${PLIC} testpass.idl
+	${PLIC} $(srcdir)/testpass.idl
 
-check-fail: plic.py testfail.idl
+check-fail:	${PLIC} testfail.idl
 	echo -n "testfail.idl: checked:" ; \
 	egrep -vn '^(//.*|\s*)$$' $(srcdir)/testfail.idl | sed 's/:/ /' | \
 	  while read num line ; do \
 	    echo -e "namespace X {\n $$line \n}" > xgen-testfail.idl \
-	    && ! $(srcdir)/plic.py xgen-testfail.idl > /dev/null 2>&1 \
-	    || { echo -e "\ntestfail.idl:$$num: no error: $$line" ; exit 1 ; } ; \
+	      && ! ${PLIC} xgen-testfail.idl > /dev/null 2>&1 \
+	      || { echo -e "\ntestfail.idl:$$num: no error: $$line" ; exit 1 ; } ; \
 	    echo -n " $$num" ; \
 	  done ; echo
 	rm -f xgen-testfail.idl
 
 clean:
-	rm -f xgen-$(@F) plic.py
+	rm -f xgen-$(@F)
