plic/: Test IDL parser checks.
* plic.g: added 'record' to keyword list. check enum value names to be
undefined identifiers. exit with exit_status != 0 on parse errors.

* testfail.idl: provide invalid idl statements to test parser checks.

* testpass.idl: renamed from test.idl.

* Makefile: test testfail.idl line-by-line for invalid idl statements.

diff --git a/plic/Makefile b/plic/Makefile
--- a/plic/Makefile
+++ b/plic/Makefile
@@ -15,8 +15,21 @@ plic.py: plic.g
 	cp xgen-$(@F) $@
 	rm -f xgen-$(@F) xgen-$(@F).errors
 
-check:	plic.py test.idl
-	$(srcdir)/plic.py test.idl
+check:	check-pass check-fail
+
+check-pass:	plic.py testpass.idl
+	./plic.py $(srcdir)/testpass.idl
+
+check-fail: plic.py testfail.idl
+	echo -n "testfail.idl: checked:" ; \
+	egrep -vn '^(//.*|\s*)$$' $(srcdir)/testfail.idl | sed 's/:/ /' | \
+	  while read num line ; do \
+	    echo -e "namespace X {\n $$line \n}" > xgen-testfail.idl \
+	    && ! $(srcdir)/plic.py xgen-testfail.idl > /dev/null 2>&1 \
+	    || { echo -e "\ntestfail.idl:$$num: no error: $$line" ; exit 1 ; } ; \
+	    echo -n " $$num" ; \
+	  done ; echo
+	rm -f xgen-testfail.idl
 
 clean:
 	rm -f xgen-$(@F) plic.py ChangeLog
